// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVRY4wfhFV17u1IvWVgYsS73gcIdJjw3A',
    appId: '1:12293634670:web:8c0aa7935f578ee37e847f',
    messagingSenderId: '12293634670',
    projectId: 'securiteinfo-cdf92',
    authDomain: 'securiteinfo-cdf92.firebaseapp.com',
    storageBucket: 'securiteinfo-cdf92.appspot.com',
    measurementId: 'G-B7H5YD1DX4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3WAuNzLfr8RwemmNVgQI1Y8nwX3LwihU',
    appId: '1:12293634670:android:bc4135472d4e89187e847f',
    messagingSenderId: '12293634670',
    projectId: 'securiteinfo-cdf92',
    storageBucket: 'securiteinfo-cdf92.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnxqjKr8_Zwmfwv7SM7gYvsZwcJBCBoCM',
    appId: '1:12293634670:ios:26002828088b8eba7e847f',
    messagingSenderId: '12293634670',
    projectId: 'securiteinfo-cdf92',
    storageBucket: 'securiteinfo-cdf92.appspot.com',
    iosBundleId: 'com.example.babysitter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnxqjKr8_Zwmfwv7SM7gYvsZwcJBCBoCM',
    appId: '1:12293634670:ios:26002828088b8eba7e847f',
    messagingSenderId: '12293634670',
    projectId: 'securiteinfo-cdf92',
    storageBucket: 'securiteinfo-cdf92.appspot.com',
    iosBundleId: 'com.example.babysitter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVRY4wfhFV17u1IvWVgYsS73gcIdJjw3A',
    appId: '1:12293634670:web:8c0aa7935f578ee37e847f',
    messagingSenderId: '12293634670',
    projectId: 'securiteinfo-cdf92',
    authDomain: 'securiteinfo-cdf92.firebaseapp.com',
    storageBucket: 'securiteinfo-cdf92.appspot.com',
    measurementId: 'G-B7H5YD1DX4',
  );
}
